name: 'Test Create Customer'
description: 'Replicated Create Customer'
inputs:
  replicated-app:
    description: 'Replicated App Slug.'
    required: true
    default: ''
  replicated-api-token:
    description: 'Replicated API Token.'
    required: true
    default: ''
  customer-name:
    description: 'Name of the customer.'
    required: true
  customer-email:
    description: 'Email of the customer.'
    required: false
  channel:
    description: 'Channel to assign the customer to.'
    required: true
    default: '${GITHUB_REF}'
outputs:
  customer-id: # id of the customer
    description: 'Contains the customer id.'
    value: ${{ steps.cli-create-customer.outputs.customer-id }}
  license-id: # id of the license
    description: 'Contains the license id.'
    value: ${{ steps.cli-get-customer-license-id.outputs.license-id }}
runs:
  using: "composite"
  steps:
    - name: 'Init'
      shell: bash
      run: |
        pwd
        ls -la
        echo github1: ${{ github.action_path }}
        echo github2: ${GITHUB_ACTION_PATH}
    - name: 'Replicated CLI create customer'
      id: 'cli-create-customer'
      uses: jdewinne/gh-actions/cli-create-customer@v0.0.1
      with:
        replicated-app: ${{ inputs.replicated-app }}
        replicated-api-token: ${{ inputs.replicated-api-token }}
        customer-name: ${{ inputs.customer-name }}
        customer-email: ${{ inputs.customer-email }}
        channel: ${{ inputs.channel }}
    - name: 'Replicated CLI get customer license id'
      id: 'cli-get-customer-license-id'
      uses: jdewinne/gh-actions/cli-get-license-id@v0.0.1
      with:
        replicated-app: ${{ inputs.replicated-app }}
        replicated-api-token: ${{ inputs.replicated-api-token }}
        customer: ${{ steps.cli-create-customer.outputs.customer-id }}