name: 'TEST CLI create customer'
description: 'CLI: Create a Customer'
inputs:
  replicated-app:
    description: 'Replicated App Slug.'
    required: true
    default: ''
  replicated-api-token:
    description: 'Replicated API Token.'
    required: true
    default: ''
  customer-name:
    description: 'Name of the customer.'
    required: true
  customer-email:
    description: 'Email of the customer.'
    required: false
  channel:
    description: 'Channel to assign the customer to.'
    required: true
    default: '${GITHUB_REF}'
outputs:
  customer-id: # id of the customer
    description: 'Contains the customer id.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - customer
    - create
    - --name=${{ inputs.customer-name }}
    - --channel=${{ inputs.channel }}
    - --email=${{ inputs.customer-email }}
    - --output=json
  env:
    REPLICATED_APP: ${{ inputs.replicated-app }}
    REPLICATED_API_TOKEN: ${{ inputs.replicated-api-token }}